### ISSUE TITLE
cannot download an album

### ISSUE THREAD

**Issue by dineshkoravi** [prabaprakash/Saavn-Downloader#39]
it wont download this album.

https://www.jiosaavn.com/album/what-is-psych/jXKhstjC--c_

Output:
```
Enter the url:https://www.jiosaavn.com/album/what-is-psych/jXKhstjC--c_
...
Initiating Album Downloading
Album name:  What Is Psych?
Downloading Bury My Burden.m4a
...
Please paste link of album or playlist
```

**Comment by prabaprakash** [comment]
Fixed it, working good.

**Comment by dineshkoravi** [comment]
No. It does not work still. Check below.

```
(saavn) F:\Git\Saavn-Downloader>python Download.py
C:\Users\korav\Envs\saavn\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Enter album/playlist url: https://www.jiosaavn.com/album/what-is-psych/jXKhstjC--c
Downloading Album
Album name:  What Is Psych?
Downloading Bury My Burden.m4a
Please paste album/playlist url

```
Let me know if im doing something wrong.

**Comment by prabaprakash** [comment]
Checking it @dineshkoravi

**Comment by prabaprakash** [comment]
@dineshkoravi  The error was occurred while creating folder in windows with these name "What Is Psych?". Question mark isn't allowed in folder creation. fixed it. closing the issue

**Comment by dineshkoravi** [comment]
Thankyou. But I am still unable to download another album now.

Album : https://www.jiosaavn.com/album/layilo-from-layilo/krxTbUvvK84_

```
Enter album/playlist url: https://www.jiosaavn.com/album/layilo-from-layilo/krxTbUvvK84_
Please paste album/playlist url

```

**Comment by dineshkoravi** [comment]
I think this is due to change in Saavn UI code. its not parsing data properly.
